<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for a3exception</title>
  </head>
  <body>
    <h1>Links for a3exception</h1>
<a href="https://files.pythonhosted.org/packages/df/49/d3970281a11f3af8906c003f063faf9baf46d0e16b4b2dd0761f80f6b7c1/a3exception-0.1.0.tar.gz#sha256=ad4e5b1c1053e6610af3355c9a511e1e7645b837728cda08b2b46c0995a26b88" data-requires-python="&gt;=3.8" >a3exception-0.1.0.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/da/69/2c93fabceb95ccf75ed96c82452ba241f97066411747cf413b961fddb830/a3exception-0.1.1.tar.gz#sha256=8b3ec91d94e868918c65e6bb172d0e1795a1782af5373feed4884bc7e97d1703" data-requires-python="&gt;=3.8" >a3exception-0.1.1.tar.gz</a><br />
</body>
</html>
<!--SERIAL 21949800-->