<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for adaptix</title>
  </head>
  <body>
    <h1>Links for adaptix</h1>
<a href="https://files.pythonhosted.org/packages/e2/e8/36649d84750f0e8b7e5cde9303a2230561b77a18caedacd0685ebe2dca67/adaptix-3.0.0a1-py3-none-any.whl#sha256=a05255d5529529da56c4af99b9882a129d6558a484e57d32b33afe29c37eab35" data-requires-python="&gt;=3.8" >adaptix-3.0.0a1-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/cf/89/890a35e84d449c1ceecefc4e36dab022cd626479c6e62597ddcb6d06785f/adaptix-3.0.0a2-py3-none-any.whl#sha256=4d92af0f4e59fd0afe80897e59a1352892ccc53e43a0a5102698a2c96b58ffa2" data-requires-python="&gt;=3.8" >adaptix-3.0.0a2-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/50/dd/d71c98a5e8cefb27a74f0b3216f3fc889e74526a3a9547f4babff6d87954/adaptix-3.0.0a2.tar.gz#sha256=115f5e3ba3272790eeb08507373e540ac002039faab5af0713f75873994b35aa" data-requires-python="&gt;=3.8" >adaptix-3.0.0a2.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/4d/da/ab351efd79b029b67484da6eab51926fb255abda676805a5d66024143666/adaptix-3.0.0a3-py3-none-any.whl#sha256=a72aaa19b828550740df6d1bd7efef8e221cd67fc4f96cf1c1604baa75201989" data-requires-python="&gt;=3.8" >adaptix-3.0.0a3-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/a1/8c/b3d2b1c8d8a1874063d3e7e7c2bbecd437231bf4cbf042dd0eb28a0dab92/adaptix-3.0.0a3.tar.gz#sha256=903417848161e9d546e9697f7297826072afda8119ba742bec4e57009bf64948" data-requires-python="&gt;=3.8" >adaptix-3.0.0a3.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/f5/0d/5c8dc1ef0cc4b0853acfb19e112b0deb2cf77e5a91b5a44d942ecfc61f6a/adaptix-3.0.0a4-py3-none-any.whl#sha256=d46aeb99ef9b13b8b4ec272438dd77b201cc1541c6f1e9272b20add44fb4ebd8" data-requires-python="&gt;=3.8" data-dist-info-metadata="sha256=a6309107a13ecc2300f6d11157f4a50030db46510ecda607093b050327735981" data-core-metadata="sha256=a6309107a13ecc2300f6d11157f4a50030db46510ecda607093b050327735981">adaptix-3.0.0a4-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/d6/00/dfda48d626d9532dbf488f9988fca3180fb997546bd0bc41ae86c746900b/adaptix-3.0.0a4.tar.gz#sha256=bdaeacbe24f3a712d80cad540fa70a5868d5079dd9d5cb9b91984b8bd656eee1" data-requires-python="&gt;=3.8" >adaptix-3.0.0a4.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/e0/c9/bf561fcacce162a672c74adcfce24fd8cdfe408b09fc193f4e426d525e34/adaptix-3.0.0a5-py3-none-any.whl#sha256=f890125e5cdef1d41844466f2556bbc86d3a79f4e06cd1fd22f3879ce9eb8b9a" data-requires-python="&gt;=3.8" data-dist-info-metadata="sha256=1f24940880964e506109c1bb793ecb93a5c9b4588014920ae5adb8c07baa119e" data-core-metadata="sha256=1f24940880964e506109c1bb793ecb93a5c9b4588014920ae5adb8c07baa119e">adaptix-3.0.0a5-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/c2/f0/861c6b6189b3a009a727fa73c3edb78756e96b433e56c019b0bc7e79ec14/adaptix-3.0.0a5.tar.gz#sha256=747b130cb8a056bd3bfb4614d90ece78b47b7a031dd5b0d33ce176b2b8c61265" data-requires-python="&gt;=3.8" >adaptix-3.0.0a5.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/0d/3b/54dbf452c4deb7be88dbebe98a593e7b374d2038228726bbba92d3b0d2f9/adaptix-3.0.0a6-py3-none-any.whl#sha256=14ea63062f49068802a561e9815b18bfa78b5defe68bfca29ba7aa02d21f1c0f" data-requires-python="&gt;=3.8" data-yanked="An obscure bug at model dumper was found, that occurred if the field name was the same as the internal variable. Use 3.0.0a7 which contains only bugfix" data-dist-info-metadata="sha256=629ec3c88ea7956db8b9b9b1b1a2a609c49ea38fcaaa1fcd1d43f02bd5aa3b41" data-core-metadata="sha256=629ec3c88ea7956db8b9b9b1b1a2a609c49ea38fcaaa1fcd1d43f02bd5aa3b41">adaptix-3.0.0a6-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/ff/15/e2c523303d2e7b7b936e589bff03edee810f550276e758d7c0bab760d273/adaptix-3.0.0a6.tar.gz#sha256=22eb8151014e4de85bdb19330a03c868057d3f1a1cf518d4425e85836b40f95c" data-requires-python="&gt;=3.8" data-yanked="An obscure bug at model dumper was found, that occurred if the field name was the same as the internal variable. Use 3.0.0a7 which contains only bugfix" >adaptix-3.0.0a6.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/7d/60/6c620a5c1c831e1905289d927252f2a037ba3aa82175b29320f8af432d3f/adaptix-3.0.0a7-py3-none-any.whl#sha256=8c4fbd1fe9b102f5e8b8fd2faafa2afe4e911b0c5df1480086b8a62ea859c997" data-requires-python="&gt;=3.8" data-dist-info-metadata="sha256=024582cc1aad469e37d678a484504e32975a8bbe6dd0c25f767b6e29a8de752c" data-core-metadata="sha256=024582cc1aad469e37d678a484504e32975a8bbe6dd0c25f767b6e29a8de752c">adaptix-3.0.0a7-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/0c/fb/5a0b33ef88da462b3e34aeffffbcb3013d37edba24fee89e1f949c7061b7/adaptix-3.0.0a7.tar.gz#sha256=f8a4b7fd8babe4c4572f66823de0c6a799765fdef98569b4105ce6d185aa9b1f" data-requires-python="&gt;=3.8" >adaptix-3.0.0a7.tar.gz</a><br />
<a href="https://files.pythonhosted.org/packages/b9/c8/9da4ffb3bb7cd1f526443879ae45bbe904f10751437cf891dfe528f69c79/adaptix-3.0.0a8-py3-none-any.whl#sha256=54806ce13abcd74d6f2f7058ccf25ad3e1dd8d09303b28824496ae95d261be76" data-requires-python="&gt;=3.8" data-dist-info-metadata="sha256=7218fea6336f3e73e99e3d8b161ddc08c9efd0fb3a9f373a095c9575d356b937" data-core-metadata="sha256=7218fea6336f3e73e99e3d8b161ddc08c9efd0fb3a9f373a095c9575d356b937">adaptix-3.0.0a8-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/e0/31/c303cef063da68616819609ecd5f09ac0f2616b33848dadb3171a540975c/adaptix-3.0.0a8.tar.gz#sha256=4da7194f81ae91b747536177e6874f60dc27ea34e752e39a44583526c16b40a4" data-requires-python="&gt;=3.8" >adaptix-3.0.0a8.tar.gz</a><br />
</body>
</html>
<!--SERIAL 20693623-->