<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for odoo-addon-purchase-exception</title>
  </head>
  <body>
    <h1>Links for odoo-addon-purchase-exception</h1>
    <a href="https://files.pythonhosted.org/packages/ac/b9/f1d77fbd5ac0fa1500bef6665ab980c017a1115655155dee59bffe0a60c6/odoo_addon_purchase_exception-15.0.1.0.0.2-py3-none-any.whl#sha256=884b7b1b49ddf9e77251191197587c05e24d8dc793d7cfec7d9049c5042ac978" data-requires-python="&gt;=3.8" >odoo_addon_purchase_exception-15.0.1.0.0.2-py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 15223911-->