<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for odoo-addon-purchase-request-exception</title>
  </head>
  <body>
    <h1>Links for odoo-addon-purchase-request-exception</h1>
    <a href="https://files.pythonhosted.org/packages/c0/91/b7a7966bccba18e405b356e8a959bd88a2687175df3b261d91fc307db30f/odoo_addon_purchase_request_exception-15.0.1.0.0.2-py3-none-any.whl#sha256=5e5e23e7cae27711da41c7995534598840aaf296f227ea6985c326a5c6f35fd8" data-requires-python="&gt;=3.8" >odoo_addon_purchase_request_exception-15.0.1.0.0.2-py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 17301209-->