<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for odoo-addon-purchase-exception</title>
  </head>
  <body>
    <h1>Links for odoo-addon-purchase-exception</h1>
    <a href="https://files.pythonhosted.org/packages/ac/b9/f1d77fbd5ac0fa1500bef6665ab980c017a1115655155dee59bffe0a60c6/odoo_addon_purchase_exception-15.0.1.0.0.2-py3-none-any.whl#sha256=884b7b1b49ddf9e77251191197587c05e24d8dc793d7cfec7d9049c5042ac978" data-requires-python="&gt;=3.8" >odoo_addon_purchase_exception-15.0.1.0.0.2-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/c3/32/806f0eb545d49ca91df928b2a22a55987286de1293ee7d7fb18f7663ba62/odoo_addon_purchase_exception-16.0.1.0.0.4-py3-none-any.whl#sha256=c4a8e44dc1664e40e2fd0b2664287ebf1e2880a8f1552238656740affc2b8de2" data-requires-python="&gt;=3.10" >odoo_addon_purchase_exception-16.0.1.0.0.4-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/d7/20/0a17ecbab28e9c80b8f65d834f0249e6249e302d0a572041f363bc7f2699/odoo_addon_purchase_exception-16.0.1.0.0.5-py3-none-any.whl#sha256=0b37f4a16a77ac2910997d072b636fb1731c0c4b8c4333572742bdb0f44d547a" data-requires-python="&gt;=3.10" >odoo_addon_purchase_exception-16.0.1.0.0.5-py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 17427998-->