<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for odoo14-addon-purchase-exception</title>
  </head>
  <body>
    <h1>Links for odoo14-addon-purchase-exception</h1>
    <a href="https://files.pythonhosted.org/packages/1a/31/b9b4588db0127d073ea3ed524b550c7aa2fa28c77a3db6df1dfed8d7462c/odoo14_addon_purchase_exception-14.0.1.0.1.dev2-py3-none-any.whl#sha256=75929a66b3730524074c70e4f81c9507d3bb50638e619cae6c36b9d9b4724cfa" data-requires-python="&gt;=3.6" >odoo14_addon_purchase_exception-14.0.1.0.1.dev2-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/a1/3d/dc1a6bd4545c1ddfad9e56559aa29edb3ea3f5d764d89bdc0b463fd2e483/odoo14_addon_purchase_exception-14.0.1.0.1.dev3-py3-none-any.whl#sha256=8312725eb87a1d8b5a8ead001331f5f921964e49e5bd439ce842a4aa26da1e5a" data-requires-python="&gt;=3.6" >odoo14_addon_purchase_exception-14.0.1.0.1.dev3-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/c2/c4/b742e5e1c016891ce1476f682d3b950f2416e6c510261eb2ab5520802fe7/odoo14_addon_purchase_exception-14.0.1.0.1.dev4-py3-none-any.whl#sha256=e84a73df3afb800b76dae5c8abfb5044ba6b4d5b6dd0c55b6776f02c58386409" data-requires-python="&gt;=3.6" >odoo14_addon_purchase_exception-14.0.1.0.1.dev4-py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 14746450-->