<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for odoo-addon-hr-expense-exception</title>
  </head>
  <body>
    <h1>Links for odoo-addon-hr-expense-exception</h1>
    <a href="https://files.pythonhosted.org/packages/5d/b5/a15b94439a0a089d3267bb730c5245fde4e827961778131b1c02277b3f0b/odoo_addon_hr_expense_exception-15.0.1.0.0.2-py3-none-any.whl#sha256=37c03dfefc300e944cf8a62bdac97f5c64aa497508057ac55df31f8c79d48b4e" data-requires-python="&gt;=3.8" >odoo_addon_hr_expense_exception-15.0.1.0.0.2-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/00/91/86909568a9a70f388b67a05021c99035b532a853685166fd04a2afc4d801/odoo_addon_hr_expense_exception-15.0.1.0.0.3-py3-none-any.whl#sha256=12b984917434886bcbeb675798fdbbac9f7eb4241a3271543d39b0b0f4274fc9" data-requires-python="&gt;=3.8" data-dist-info-metadata="sha256=1466bb50c5176bfdb1dedc8f3b4d25067767fdde33ac03cdfa53c9574bc50e2e" data-core-metadata="sha256=1466bb50c5176bfdb1dedc8f3b4d25067767fdde33ac03cdfa53c9574bc50e2e">odoo_addon_hr_expense_exception-15.0.1.0.0.3-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/1f/f5/1a9b8bd873fb2116f0b1d6b920ff147b53e4459713d8517e310b6ca46bd1/odoo_addon_hr_expense_exception-15.0.1.0.0.4-py3-none-any.whl#sha256=265a13a961057c110e6de496c1b413c0bfa1f6c856447de8ae20b3d7c3d3c104" data-requires-python="&gt;=3.8" data-dist-info-metadata="sha256=0b9c2ef3e723718b1c5719db41871ca5376bb2c9c4f5be7add084acd274ceebf" data-core-metadata="sha256=0b9c2ef3e723718b1c5719db41871ca5376bb2c9c4f5be7add084acd274ceebf">odoo_addon_hr_expense_exception-15.0.1.0.0.4-py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 18749917-->