<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for odoo-addon-stock-exception</title>
  </head>
  <body>
    <h1>Links for odoo-addon-stock-exception</h1>
<a href="https://files.pythonhosted.org/packages/3b/78/4265532ccc972b92ff65da6cd3dd2beb49c7c2fd1d59f6ef9ebe8766b234/odoo_addon_stock_exception-16.0.1.0.0.1-py3-none-any.whl#sha256=f34a8b622c68ba4dc73bdb523358a22674a6ca5df7e31ecafb736cba1ad04b95" data-requires-python="&gt;=3.10" data-dist-info-metadata="sha256=700fb5db14b94b13d802a1a53446a176b619be489036de6f8b10bf2548156275" data-core-metadata="sha256=700fb5db14b94b13d802a1a53446a176b619be489036de6f8b10bf2548156275">odoo_addon_stock_exception-16.0.1.0.0.1-py3-none-any.whl</a><br />
</body>
</html>
<!--SERIAL 23325656-->