<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for odoo-addon-purchase-exception</title>
  </head>
  <body>
    <h1>Links for odoo-addon-purchase-exception</h1>
    <a href="https://files.pythonhosted.org/packages/ac/b9/f1d77fbd5ac0fa1500bef6665ab980c017a1115655155dee59bffe0a60c6/odoo_addon_purchase_exception-15.0.1.0.0.2-py3-none-any.whl#sha256=884b7b1b49ddf9e77251191197587c05e24d8dc793d7cfec7d9049c5042ac978" data-requires-python="&gt;=3.8" >odoo_addon_purchase_exception-15.0.1.0.0.2-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/41/f1/e58a960f4097711bf37b71063a403dc0fe8481aa72401d5c2f3b5161135d/odoo_addon_purchase_exception-15.0.1.0.0.4-py3-none-any.whl#sha256=a5f5da1b8a378c10d12f0c6c526a814ec4a494bc650333715c9950c9de8cb29b" data-requires-python="&gt;=3.8" data-dist-info-metadata="sha256=8d0b888bba5a4efdece97466eed7ceb31ccbe3485ba30cd3e98501a75cc586f3" data-core-metadata="sha256=8d0b888bba5a4efdece97466eed7ceb31ccbe3485ba30cd3e98501a75cc586f3">odoo_addon_purchase_exception-15.0.1.0.0.4-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/c3/32/806f0eb545d49ca91df928b2a22a55987286de1293ee7d7fb18f7663ba62/odoo_addon_purchase_exception-16.0.1.0.0.4-py3-none-any.whl#sha256=c4a8e44dc1664e40e2fd0b2664287ebf1e2880a8f1552238656740affc2b8de2" data-requires-python="&gt;=3.10" >odoo_addon_purchase_exception-16.0.1.0.0.4-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/d7/20/0a17ecbab28e9c80b8f65d834f0249e6249e302d0a572041f363bc7f2699/odoo_addon_purchase_exception-16.0.1.0.0.5-py3-none-any.whl#sha256=0b37f4a16a77ac2910997d072b636fb1731c0c4b8c4333572742bdb0f44d547a" data-requires-python="&gt;=3.10" >odoo_addon_purchase_exception-16.0.1.0.0.5-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/2d/6a/66ab71af458ab625094e00fc4accc9a9a82768ff39183d5ef64b755034b8/odoo_addon_purchase_exception-16.0.1.0.0.7-py3-none-any.whl#sha256=84c3c54095fb91e5a7d860c4bf179e844b8bbc10ce713162a176fc9512c1f9bd" data-requires-python="&gt;=3.10" data-dist-info-metadata="sha256=8d71e246a127fd67fd9bab729e40670af684ae0c71ffddb4b0c093b0b75dc1cf" data-core-metadata="sha256=8d71e246a127fd67fd9bab729e40670af684ae0c71ffddb4b0c093b0b75dc1cf">odoo_addon_purchase_exception-16.0.1.0.0.7-py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 18978801-->