<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for odoo14-addon-hr-expense-exception</title>
  </head>
  <body>
    <h1>Links for odoo14-addon-hr-expense-exception</h1>
    <a href="https://files.pythonhosted.org/packages/c1/3f/00c40203a3d19af5f4e14cf904989e0248c263b8b8f34f8dcf65686ef924/odoo14_addon_hr_expense_exception-14.0.1.0.1.dev2-py3-none-any.whl#sha256=4789f91a55dc4f659ea05af97840bcf57f69e89b78efde86318dc721f29201d4" data-requires-python="&gt;=3.6" >odoo14_addon_hr_expense_exception-14.0.1.0.1.dev2-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/19/c6/186ae97ca4896b460c5a0c5bf1d4586ae58eed2eb0282b7d9eacff1d6c04/odoo14_addon_hr_expense_exception-14.0.1.0.1-py3-none-any.whl#sha256=531d94653efb7e74ae539964ec3f7587a0aee6b63b403e136e5ae2a62a2ecc1f" data-requires-python="&gt;=3.6" >odoo14_addon_hr_expense_exception-14.0.1.0.1-py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 12419782-->