<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for odoo13-addon-product-exception</title>
  </head>
  <body>
    <h1>Links for odoo13-addon-product-exception</h1>
<a href="https://files.pythonhosted.org/packages/ff/8e/f162629131e5fa771a0985b4d8e0590614ca370dcb2df9ba982d678f7dd3/odoo13_addon_product_exception-13.0.1.0.1-py3-none-any.whl#sha256=277130e9334c1aea3461a22d90a4c3141b88c136974017467ea18744ff894dca" data-requires-python="&gt;=3.5" data-dist-info-metadata="sha256=725279ea35cf2b6cf61384106ef4d66a543ae598351f26445799c29ae25c6c54" data-core-metadata="sha256=725279ea35cf2b6cf61384106ef4d66a543ae598351f26445799c29ae25c6c54">odoo13_addon_product_exception-13.0.1.0.1-py3-none-any.whl</a><br />
<a href="https://files.pythonhosted.org/packages/05/2b/53e12361adab2c24f6b78a4b768885fbd88de8d8d99a3599b9476196064f/odoo13_addon_product_exception-13.0.1.0.2.dev1-py3-none-any.whl#sha256=d3b4ed1c38b8ecdc7324253549b32a09208edd29fafcdb7f8704ad1c157da1fb" data-requires-python="&gt;=3.5" data-dist-info-metadata="sha256=73696e97f93dc256087b9fa49d16d216656749e91c2d1217e45bcb23bc4b15b3" data-core-metadata="sha256=73696e97f93dc256087b9fa49d16d216656749e91c2d1217e45bcb23bc4b15b3">odoo13_addon_product_exception-13.0.1.0.2.dev1-py3-none-any.whl</a><br />
</body>
</html>
<!--SERIAL 19585892-->