<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for upy-error</title>
  </head>
  <body>
    <h1>Links for upy-error</h1>
    <a href="https://files.pythonhosted.org/packages/52/3a/9fca8d8fd262fe576956a3c8024f5b4ea102ce63eb31f75fea5fa7f78954/upy-error-0.0.1.tar.gz#sha256=609dfc46bfd410adbdcdfd5966633bfb8b9bc2b012df549f94ba75f9fce78fde" data-requires-python="&gt;=3.6" >upy-error-0.0.1.tar.gz</a><br />
    <a href="https://files.pythonhosted.org/packages/e2/04/00d40500da9470131aeff569716c3be3d5a2f8c0b5a8c5eea6b7332d7fde/upy_error-0.0.1-py2.py3-none-any.whl#sha256=8ce1c4d6b83e16167bf6c803053054cc264b8994f21d6fca37d16ef9c3d48df5" data-requires-python="&gt;=3.6" >upy_error-0.0.1-py2.py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/32/af/0c26dbe990fde40cfa6f32d1725d51a410eeebfa3c02236cfe83f55e2e2f/upy-error-0.0.2.tar.gz#sha256=1443e61ba8ec8c610ad761de20b3ea1604927fe876fdbb096afe043e72c7f383" data-requires-python="&gt;=3.6" >upy-error-0.0.2.tar.gz</a><br />
    <a href="https://files.pythonhosted.org/packages/ab/c4/6abdc541f1478543f7aa05298ec0e75825b6e5272e87f7a75230f2913b1b/upy_error-0.0.2-py2.py3-none-any.whl#sha256=42ce128f084f6f6a02f53a19fc86ff8b2fc9b61f379f7343b16e7235d65916c2" data-requires-python="&gt;=3.6" >upy_error-0.0.2-py2.py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 14522395-->